"""seed CFIHOS document type and representation type classification schemes

Revision ID: 20260909_0052
Revises: 20260909_0051
Create Date: 2026-09-09 00:00:00.000000

Follow-on to SM-P0-04. Specification section 7.6 names Industry/Application
and Drawing Type as desirable schemes beyond the three the catalogue already
had. SM-P0-04 created neither, because neither had a vocabulary to seed from
and inventing one is what CLAUDE.md forbids.

CFIHOS v2.0 CORE supplies one of them. This migration seeds two schemes from
it, and no assignment rows:

* **Document Type** -- 329 nodes, the CFIHOS CORE `document type` vocabulary.
  This is the scheme section 7.6 calls "Drawing Type": it carries `2365`
  piping and instrumentation diagram, `0980` block diagram, `4018` general
  arrangement diagram, `4780` logic diagram. It is seeded under CFIHOS's own
  name rather than "Drawing Type" because the vocabulary is a *document* type
  list -- 329 entries including "audit plan" -- and cutting it down to only
  the drawing-shaped entries would mean inventing the boundary. Section 7.6's
  drawing-type facet is served by filtering this scheme.
* **Representation Type** -- 5 nodes, the distinct values of the
  `representation type` column on CFIHOS `discipline document type`. This one
  the specification never named, and it is the most directly section 7.8
  (representation-oriented) facet in the source: intelligent vector drawing
  (CAD), raster image, structured data, text, multi media.

Industry/Application is still not created. CFIHOS does not supply it -- it is
a single-industry standard by construction, and its nearest columns
(`asset type reference`, six values) describe asset granularity, not
industry. The gap stands rather than being filled with an invention.

`node_code` differs between the two schemes on purpose. Document Type uses
CFIHOS's own four-digit short code, which is the code document-control
systems actually carry and is unique across all 329; minting our own codes
where the source has a governed code system would create reconciliation debt.
Representation Type has no source code -- the values are free text in a
column -- so its codes are derived from the labels, as SM-P0-04's three
schemes are. `node_code` is unique per scheme, so a scheme defining its own
code system is exactly what the column is for.

Two source data-quality decisions, both recorded rather than silently
applied:

* `representation type` contains both `Text` (607 rows) and `text` (1 row).
  Folded to one node.
* It also contains `not specified` (94 rows). That is the absence of a value,
  not a value, so it is not a node.

Source provenance. Both schemes carry `version_label = "CFIHOS v2.0"`.
The vocabulary is extracted from CORE-CFIHOS-CSV-v2.0.zip, published at
https://www.jip36-cfihos.org/cfihos-standards/, sha256
a69b98012d9e4a46495a3aed48eef8ce75a69d001eaa28b4c38cb0f3c921909d.
The archive itself is not committed; this migration is the extract, and the
hash above is what makes the extract auditable against the published release.
Bulk CFIHOS reference-data ingestion -- the 832 equipment classes, 875 tag
classes, 11890 RDL objects and 3091 cross-scheme mappings in the same
archive -- is deliberately out of scope here. Those are a versioned external
dependency and belong to SM-P2-02 through the
ExternalSemanticScheme/ExternalSemanticSchemeVersion machinery SM-P0-03
built, with a release label and checksum, driven by a connector rather than
by a migration.

`sort_order` follows the source file's own ordering, which is alphabetical by
name, in multiples of ten.
"""
from __future__ import annotations

import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260909_0052"
down_revision: Union[str, None] = "20260909_0051"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SORT_ORDER_STEP = 10
_SEED_VERSION_LABEL = "CFIHOS v2.0"

_DOCUMENT_TYPE_SCHEME = (
    "DOCUMENT-TYPE",
    "Document Type",
    "Document type facet, seeded from the CFIHOS v2.0 CORE document type reference data "
    "published by IOGP JIP36 / CFIHOS.",
)

_REPRESENTATION_TYPE_SCHEME = (
    "REPRESENTATION-TYPE",
    "Representation Type",
    "Representation type facet, seeded from the distinct representation type values in the "
    "CFIHOS v2.0 CORE discipline document type reference data.",
)

# (node_code, preferred_label, description). node_code is the CFIHOS document
# type short code. Order is the source file's own, alphabetical by name.
_DOCUMENT_TYPES: tuple[tuple[str, str, str], ...] = (
    ("4301", "action list",
     "A collection of activities tracking responsible parties and status, including but not limited to punch lists, issues lists, and check lists."),
    ("6802", "active fire protection system specification",
     "Design data and information that forms the basis of the performance specification for the active fire fighting systems (manual, foam, monitor, deluge/sprinkler systems etc.)."),
    ("4302", "alarm, trip setting list",
     "A collection of all instrument set points and/or alarms.  Each instrument having an alarm or trip function is listed. Alarms and settings are given as percentages of transmitter range and in engineering units, together with transmitter range, location of the annunciation point, cabinet, identification and relevant P&IDs/PEFS or logic drawing."),
    ("2405", "anchoring diagram",
     "A diagram showing anchoring and mooring of offshore vessels and structures and the interaction of anchor lines with sub-sea pipelines and structures."),
    ("8268", "anchoring study",
     "Includes anchoring of offshore vessels and the interaction of anchor lines with sub-sea pipelines and structures."),
    ("4303", "applicable standards list",
     "A collection of all applicable company standards, international, national and industry codes & standards that are referenced in the company standards and project specific specifications."),
    ("3304", "application software",
     "A computer program designed for a specific task or use."),
    ("1401", "approval certificate",
     "A document issued by a recognised independent authority certifying the equipment has been manufactured in accordance with code/standard. Type approval certificates are normally acceptable for proprietary items. CE mark certification or similar equivalent shall be included under this document type."),
    ("4305", "approved vendor list",
     "A collection of approved vendors and suppliers for a particular contract."),
    ("1904", "aspect data",
     "Data which further describes an element of an organisation's activities, products or services that can interact with the environment. Enhances 'aspect register'."),
    ("2305", "assembly diagram",
     "A diagram utilized for transient activity during assembly (e.g. sequence of activity) and not finished work."),
    ("5705", "asset reference plan",
     "An integrated lifecycle management and development plan for surface and sub-surface facilities, including development scenarios, and phased development plans."),
    ("5706", "assurance plan",
     "A plan assuring that standards of quality are being met by systematically monitoring and evaluating the various aspects of deliverables vs standards.  Predecessor to 'document distribution matrix'."),
    ("5707", "audit plan",
     "A document capturing what particular audits and assessments will be carried out to achieve the overall quality program.  May include an overview schedule highlighting activities."),
    ("6603", "authority matrix",
     "A list or register of people or organisations authorised to perform a range of tasks which may be technical, financial, contractual, organisational, or other. Includes Technical Authorities Matrix, Roles and Responsibilities, RACI/RASCI."),
    ("7704", "basis of design",
     "A document outlining the premise for decisions and the resulting principles that are to be followed regarding the design of the facility and comprising all process design philosophies including but not limited to environmental, drainage, ventilation, spading/isolation, plant availability/down time assessment and relief/blowdown philosophy etc."),
    ("7179", "basis of estimate",
     "A document outlining the premise for decisions and the resulting principles that are to be followed regarding estimates. This document should be updated with each formal update of the project cost estimate, particularly at each stage gate. As much detail as possible should be provided in the document, relative to the scope definition available for the compilation of the estimate."),
    ("1905", "benchmarking data",
     "A data set used to evaluate or judge project estimates and or performance relative to it (i.e., ISO 19008)."),
    ("4306", "bill of materials",
     "A list of all parts and sub assemblies that constitute a particular assembly, showing the quantity of each required item. Typically developed from analyzing a drawing."),
    ("3309", "bill of quantities",
     "A consolidated list of assemblies or bulk material showing the quantity of each required to suit a purpose. Use 'bill of materials' for sub assemblies and parts."),
    ("0980", "block diagram",
     "A schematic diagram which shows the relation between the main functions or the main component in the plant or group of plants."),
    ("6401", "budget proposal",
     "A document which captures a recommended course of action with justifications from technical and/or commercial aspects to allocate money to activities."),
    ("4308", "cable schedule",
     "A collection of values relating to List of all cables, their specifications and end points. Indicates salient features of all cables in Vendor's supply and connecting cables supplied by Principal."),
    ("2901", "cable size calculation",
     "Calculations required for sizing of cables."),
    ("1458", "calibration certificate",
     "A document certifying that an instrument shall deliver an accurate output within a set operating range."),
    ("8270", "capital spares study",
     "A consolidated study reviewing critical equipment and recommending capital spares."),
    ("2309", "cathodic protection diagram",
     "A diagram showing locations of cathodic protection and schematic diagrams."),
    ("2310", "cause and effect diagram",
     "A diagram that is showing the causes and consequences of different errors, especially related to failures in the control system."),
    ("6006", "change control procedure",
     "A procedure describing how changes through 'design', 'construction' and 'commissioning' will be managed."),
    ("6605", "change control register",
     "A consolidated register of proposed and/or processed change associated with all change to originally agreed design scope/statement of requirements, including basis for design."),
    ("3311", "change notification",
     "An advance notice to another party, e.g. another design department or fabrication facility, that there is going to be a change to a document that has been issued for construction."),
    ("3369", "change order",
     "A notification formally incorporating the change issued against existing 'contracts', 'agreements' and/or 'purchase orders' based on a change request."),
    ("6402", "change proposal",
     "A document which captures a recommended course of action with justifications from technical and/or commercial aspects to execute an activity to change something.  May lead to a change request."),
    ("7206", "change request",
     "A request, approval or rejection of changes to an existing contract. Would typically include justification and reasons for the request, and acceptance or rejection from a commercial or contractual perspective, but may also contain some technical content. For similar documents pertaining specifically to technical deviations, with no commercial/contractual content, refer to 'technical deviation request'. May be triggered by a change proposal."),
    ("4304", "check sheet",
     "A collection of specific activities to test completeness of installation or energization of a specific equipment class.  Includes collection of specific data based on testing parameters."),
    ("6919", "chemical selection report",
     "Detailed report from results of corrosion inhibition, hydrates, flow assurance, etc testing plan. Includes any preliminary testing required to establish parameters for testing."),
    ("5770", "chemical testing plan",
     "A document capturing parameters and requirements to validate selection of chemicals including but not limited to corrosion inhibitors, hydrate inhibitors, and  flow assurance chemicals."),
    ("8502", "clarification request",
     "Request (e.g., from a Contractor) for clarification of scope, technical details, or assumptions."),
    ("5799", "commissioning and startup strategy",
     "A document outlining purpose and approach for commissioning and start-up."),
    ("6048", "communication procedure",
     "A cross-discipline, internal and external communication procedure, responsibilities, and governance."),
    ("1457", "completion certificate",
     "A document certifying a scope or project activity has been successfully completed and tested for functionality."),
    ("8804", "connection diagram",
     "A diagram showing details of cable numbers and terminations point to point (e.g., to/from vendor packages, equipment)."),
    ("4321", "consolidated spare parts list",
     "A consolidated spare parts list generated to support execution of project purchasing for the purpose of commissioning, start-up, maintenance support, etc."),
    ("8382", "constructability study",
     "A document assessing sequence and method of construction of a facility to determine the best way to proceed."),
    ("2404", "construction diagram",
     "A diagram detailing assembly and fabrication."),
    ("5802", "construction schedule",
     "A time-based document outlining sequence and duration of activities related to the completion of construction scope.  Construction includes site erection and assembly but not fabrication at third party sites."),
    ("0403", "contract",
     "A binding document which records a agreement and its related mutual obligations and commitments. Typically having effect on a project or the future life of a facility. For example a sales contract, maintenance contract, etc."),
    ("5505", "control philosophy",
     "A document outlining the premise and intent for start-up and shutdown for process control. May also list instrument and control equipment, pre-alarm and shutdown alarm/trip requirements, failure modes of valves and equipment and type of signals to and from the control logic. Basis to develop more detailed control narrative."),
    ("2312", "control system diagram",
     "A pictorial representation of the main elements and functions of a control circuit/system with input/output sources (switches, relays etc.) and their relationships. Details logic functions of the circuit/system. I/O loading and cabinet layouts."),
    ("6830", "corrective action report",
     "A report detailing actions to be taken to improve a process resulting from an 'audit' or 'quality assessment'."),
    ("1780", "correspondence",
     "Any form of written communication sent or received in the course of affairs including transmittals, letters, postcards, memoranda, electronic mail, facsimiles, telegrams or cables."),
    ("6015", "cost control procedure",
     "A procedure for monitoring, controlling and reporting expenditures."),
    ("6833", "cost report",
     "A report of all costs incurred over a period of time."),
    ("6834", "cost time resource estimate report",
     "Estimate of resources (people and money) required to produce certain deliverables, typically associated with scope change. Often becomes the basis for an agreement or a contract."),
    ("7877", "country regulation specific standard",
     "A specific standard documenting additional design, construction, work process, and documentation of plant as required by local regulations. This document type shall not be used to classify the engineering technical standards (e.g. API, ISO, etc.)."),
    ("7878", "country regulation technical project documentation book",
     "A technical document describing the facilities that are proposed to be built in a country and includes all information required for regulatory approval to proceed. The document is submitted to the regulatory authorities for review and approval."),
    ("1979", "database and data set",
     "Data stored in a proprietary (e.g. SPI Watcom) or neutral (e.g. CSV) format from which multiple information contents can be generated by computer software (e.g. EDW). Includes '3D model'."),
    ("9005", "declaration of conformity",
     "Declaration that contains sufficient information to enable an recipient of the declaration of conformity to identify the issuer of the declaration, the object of the declaration, the standards and other specified requirements with which conformity is declared, and the person signing for and on behalf of the issuer of the declaration of conformity (first party)."),
    ("5801", "decommissioning plan",
     "A document capturing what particular activities and requirements will be executed and delivered to decommission and demolish (parts of) existing assets. This would include temporary assets required only for the life of the project, as well."),
    ("3322", "demonstration note on compliance",
     "A document that demonstrates that the design meets the process safety basic requirements with evidences and references to documents."),
    ("1206", "design calculation",
     "A calculations prepared in order to prove that the item of equipment or system selected meets the design criteria."),
    ("8240", "design cases study",
     "A document capturing model output defining the process design cases and sensitivity cases for process modelling."),
    ("2105", "design datasheet",
     "A datasheet which provides precise information about a  tag and compliments equipment specification."),
    ("7506", "design hse case",
     "A document outlining purpose and approach for a HSE design. Demonstrates ALARP."),
    ("8218", "design layout study",
     "A document assessing different physical configurations of a set of equipment and explaining the rationale supporting the adoption of a particular layout."),
    ("5507", "design philosophy",
     "A document outlining the premise and intent for decisions that are to be followed regarding a design. A set of ideas, beliefs, or underlying theory."),
    ("7403", "design review report",
     "A report documenting verification of a design, based on comparison with standards, constructability, operability, safety, etc. May be performed by internal or external resources."),
    ("9012", "detail diagram",
     "A diagram showing parts of a construction or a component, generally enlarged, and including specific information about the form and construction or about the assembly and joints."),
    ("9013", "dimensional report",
     "A document providing measured real dimensions and verification of tolerances."),
    ("5806", "discipline delivery plan",
     "A consolidated document describing discipline specific activities and deliverables and their criticality to drive appropriate review processes.  This is a starting point for document distribution matrix stating quality assurance and control requirements."),
    ("8202", "dispersion study",
     "A document detailing the dispersion of atmospheric releases from flaring, venting, and exhaust from compressors and machinery as well as dispersion of leaks to ground or water."),
    ("6610", "document distribution matrix",
     "A document providing an overview of distribution (workflow) process for information. Often a report out of a electronic document management system."),
    ("6017", "document, data control procedure",
     "A procedure specifically for document and data control ('information management'). Includes 'document control' charts and other procedure components."),
    ("7772", "drafting specification",
     "Rules and conventions for preparing drawings, including symbol lists, etc. may include drawing templates."),
    ("2409", "ducting and instrument diagram",
     "A schematic representation of an HVAC system indicating all HVAC equipment items and their control interfaces.  Abbreviation is typically D&ID."),
    ("8809", "earthing diagram",
     "A diagram detailing earthing (grounding) for plant and equipment and between modules and dissimilar structural elements."),
    ("9014", "elevation diagram",
     "A two-dimensional view of a three-dimensional space normally showing vertical and horizontal dimensions"),
    ("2318", "emergency exits diagram",
     "A diagram detailing escape routes, means of emergency escape/egress."),
    ("6019", "emergency response procedure",
     "A procedure detailing how the facility would respond to an emergency and how personnel would be able to evacuate. As defined for 'facilities operations' and for 'pipeline operations'."),
    ("1909", "emissions report",
     "A report detailing accumulated environmental emissions over a set period of time."),
    ("5722", "engineering schedule",
     "A time-based document outlining order in which tasks are to be carried out and the amounts of time allocated to them.  Addresses design phase as well as engineering support during manufacturing, construction, tie-in, test/inspect, shutdown."),
    ("0702", "environmental impact assessment",
     "An assessment which details the impact of facility on the surrounding environment."),
    ("6852", "environmental management system description",
     "Shall include a brief description of 'vendor's' documented 'environmental management system' showing how the system is structured and reference to the standard on which it is based (e.g. ISO 14001 or similar)."),
    ("9008", "environmental product declaration",
     "Quantified environmental information on the life cycle of a product to enable comparisons between products fulfilling the same function."),
    ("2320", "equipment cross section diagram",
     "A sliced view of a part or component that shows its internal make up."),
    ("4322", "equipment list",
     "A customized list developed to support discipline activities, extract from a Register that is used as a secondary reference (i.e. not the master). Considers all potential disciplines. Covers: conduits, panels, pipe supports, piping speciality items, lighting, etc."),
    ("3004", "equipment production criticality rating report",
     "A report documenting production criticality rating of equipment, sparing, maintenance testing and inspection requirements, spare parts requirements etc. Will feed into maintenance reference plan."),
    ("7771", "equipment specification",
     "A specification that describes the physical equipment for the purpose of procurement or fabrication. Compliments the datasheet."),
    ("5510", "equipment type selection philosophy",
     "A document outlining the premise and intent for decisions that are to be followed regarding a selection of rotating equipment. Typically provided as instruction from 'owner operator'."),
    ("0703", "escape, evacuation, rescue assessment",
     "An assessment which details the emergency evacuation and rescue means from a facility."),
    ("6856", "expediting report",
     "A report of all open purchase orders containing items scheduled to be received as of a given date, but not yet received."),
    ("5803", "fabrication schedule",
     "A time-based document outlining sequence and duration of activities related to the completion of fabrication scope at third party sites."),
    ("9001", "factory acceptance test procedure",
     "A document defining testing and acceptance criteria for the equipment as tested from factory prior to shipment."),
    ("9003", "factory acceptance test records",
     "Records demonstrating that the equipment has been tested according to the factory acceptance test procedure prior to shipment."),
    ("9010", "failure mode effects analysis",
     "A report providing analysis of the risks associated with potential technical or common cause failure of a system or item of equipment including the effect on reliability and the required function."),
    ("0502", "fatigue analysis",
     "Verification of module/substructure design for cyclic loads."),
    ("8203", "feasibility study",
     "A document assessing the practicality and/or economics of a proposed solution."),
    ("5726", "field development plan",
     "A plan providing an evaluation of field development alternatives together with the selection of an optimal development concept based on subsurface scenarios (uncertainty) and field engineering options."),
    ("0503", "finite element analysis report",
     "A report documenting method (including software) and results of finite element analysis of components."),
    ("1212", "fire extinguishant calculation",
     "Calculations to prove that a given quantity of agent will be delivered at a set rate & time. Note: Applicable to fixed fire suppression systems designed specifically for room protection.  Water mist will also be used for turbine enclosure protection."),
    ("5511", "fire protection philosophy",
     "A document outlining the premise and intent for  fire protection both passive (firewalls) and active (manual, foam, monitor, deluge/sprinkler systems etc.) in a facility."),
    ("0704", "fire, explosion assessment",
     "An assessment which details the fire and explosion propagation and risks based on facility design."),
    ("4013", "floor plan",
     "A diagram showing building, rooms, doorways, cabinet and other permanent equipment installed."),
    ("0504", "fluid analysis",
     "A report documenting compositional lab analysis of fluid streams."),
    ("2331", "foundation design diagram",
     "Details of foundation design for construction. Also see 'foundation loading diagram', specifically for loads and 'foundation layout diagram', specifically for spatial location."),
    ("2332", "foundation loading diagram",
     "A diagram detailing static and dynamic forces or movements acting on foundations or other load bearing supports, anchor bolt details, lengths and pre-tensioning. May include 'civil structural' for loads imposed, and 'civil foundations' for foundation design.  Also see 'foundation design diagram', specifically for construction details."),
    ("7770", "functional design specification",
     "A specification that describes the deliverable in terms of form, fit, function, and performance characteristics to satisfy the intended use where interpretation is required.Includes most discipline specifications describing the functionality (e.g., relief and blowdown specification, surface coating, inspection specifications, operating envelopes, etc.)."),
    ("0480", "general agreement",
     "A document which records scope and obligations as mutually agreed between two or more parties."),
    ("0580", "general analysis",
     "A report documenting  assumptions and method determining objective analysis of a set of data. Not to be used if a more specific document type can be used.  Can be used for singular/specialty deliverables which do not have a unique document type."),
    ("4018", "general arrangement diagram",
     "A diagram showing the main features and locations of major items. Usually has some dimensions to convey spatial relationships but is generally inadequate for construction."),
    ("0780", "general assessment",
     "An assessment which details a health check, GAP analysis, etc. both informal and to meet 'project management framework' requirements. Not to be used if a more specific document type can be used. Can be used for singular/specialty deliverables which do not have a unique document type."),
    ("1380", "general calculation",
     "A document showing inputs, formulas, rationale, and conclusions/mathematical results as required to enhance design or bound activities."),
    ("1580", "general certificate",
     "A document certifying compliance with specified requirements. [e.g., certificates needed for re-certifying, occupancy certificate, product certificates].Not to be used if a more specific document type can be used.  Can be used for singular/specialty deliverables which do not have a unique document type."),
    ("2321", "general diagram",
     "A diagram not otherwise described in another document type.  Not to be used if a more specific document type can be used.  Can be used for singular/specialty deliverables which do not have a unique document type."),
    ("3180", "general estimate",
     "A judgement based calculation showing a summation of cost/schedule taking into consider probabilities to develop a projected performance and should document rationale, approach, inputs, etc."),
    ("4380", "general list",
     "A collection of values with a relationship to a specific topic or object that could be either technical or business related."),
    ("4880", "general manual",
     "A document that describes methods of working to be used to accomplish an activity. Warning: this should not be a compilation of other deliverables. Not to be used if a more specific document type can be used.  Can be used for singular/specialty deliverables which do not have a unique document type."),
    ("5680", "general philosophy",
     "A document outlining the premise and intent for decisions that are to be followed regarding a specific subject. Typically provided as instruction from 'owner operator'."),
    ("5880", "general plan",
     "A document capturing what particular activities and requirements will be executed and delivered.  Typically the plan is built upon a strategy."),
    ("6180", "general procedure",
     "A document which describes a set of logically sequenced instructions to execute an activity. Not to be used if a more specific document type can be used.  Can be used for singular/speciality deliverables which do not have a unique document type."),
    ("6480", "general proposal",
     "A document which captures a recommended course of action with justifications from technical and/or commercial aspects."),
    ("6680", "general register",
     "An authoritative collection of values with a relationship to a specific topic or object that could be either technical or business related.  The columns of this collection are specified and controlled."),
    ("7180", "general report",
     "A written account of activities, conditions, occurrences, observations, or investigations at a specific time. Not to be used if a more specific document type can be used.  Can be used for singular/specialty deliverables which do not have a unique document type. May include presentation."),
    ("7280", "general request",
     "A formal contractual correspondence communicating a need for action associated with an assigned scope of work."),
    ("7480", "general review report",
     "A report documenting results of a review.  Not to be used if a more specific document type can be used.  Can be used for singular/specialty deliverables which do not have a unique document type."),
    ("5804", "general schedule",
     "A time-based document outlining sequence and duration of activities related to the completion of scope."),
    ("7880", "general specification",
     "A document formally establishing the mandatory limits or parameters which are to be met. Not to be used if a more specific document type can be used.  Can be used for singular/specialty deliverables which do not have a unique document type."),
    ("5980", "general strategy",
     "A document outlining the application of a philosophical stance for decisions and the resulting principles that are to be followed to achieve the intent. Typically developed based on a philosophy."),
    ("8380", "general study",
     "A document detailing the result of a professional evaluation and/or investigation of a specific subject. Not to be used if a more specific document type can be used.  Can be used for singular/specialty deliverables which do not have a unique document type."),
    ("6028", "handling, shipping, storage procedure",
     "A procedure indicate size of container, number off, weight, identification and contents, include detail preservation procedure detailing inspection periods, materials required etc., both prior to installation and post installation, but prior to commissioning.  Any special unpacking/handling requirements shall be stated."),
    ("0505", "hazard analysis",
     "A report identifying hazards following review exercises."),
    ("6875", "hazard and operability report",
     "A report summarizing all project HAZOP studies. To include action lists, follow up and close out action descriptions and acceptance."),
    ("6873", "hazard identification report",
     "A report summarizing all project (HAZID) exercises. Usually includes action lists, follow up, and close out action descriptions and acceptance."),
    ("6613", "hazard, effect register",
     "An authoritative collection of all individual point sources for emissions, discharge inventories and corresponding zone classifications. The columns of this collection are specified and controlled."),
    ("1415", "hazardous area certificate",
     "A document issued by a recognised independent authority certifying that a type test has satisfied the specified standards; e.g.  ATEX, BASEEFA, PTB, UL, CSA, etc. Examples of ratings include 'intrinsically safe & explosion proof'."),
    ("2334", "hazardous area classification diagram",
     "A diagram which provides information on the level of explosion proofing etc. required in each area."),
    ("0705", "health impact assessment",
     "An assessment which details the impact of facility on the health of the surrounding populace."),
    ("3342", "heat and mass balance summary",
     "A report detailing heat & mass balance for an individual design case. It will contain all required process compositions and parameters for selected locations through the process."),
    ("9015", "heat dissipation calculation",
     "Calculations of the produced heat load in order to enable HVAC sizing."),
    ("2398", "heat tracing diagram",
     "A diagram detailing electrical tracing. Includes anchoring and expansion joint details where applicable. Drawings to indicate thicknesses, specification and limit of application."),
    ("6026", "heat treatment procedure",
     "A procedure detailing heating, soak, cooling parameters, limits of strain during forming, temperature ranges, method of attachment of thermocouples, temperature control, equipment calibration, production testing, etc."),
    ("7176", "heat treatment records",
     "A report documenting method and results of heat treatment. Typically includes pyrometric charts or certificates confirming the heat treatment cycles have been conducted to 'purchasers' requirements."),
    ("2335", "hook up diagram",
     "A diagram which may show the instrument impulse, pneumatic and electronic connections, pipe work, valves, fittings, flanges and support details with associated material take-off list. Used for removal/hook up purposes and modifications."),
    ("2407", "hvac flow diagram",
     "A schematic diagram depicting an HVAC ducting system, including all items of duct mounted equipment complete with tag numbers, flow rate and duct sizing information."),
    ("4603", "hydraulic calculation",
     "Calculations to indicate basis on which equipment is sized, including pipe friction losses, equipment elevations and terminal point static pressures. Includes 'net positive suction head' calculations and other steady state conditions. Also includes calculation of hydraulic surge (synonym 'water hammer') for the purpose of determining valve sizing, closing speed, etc."),
    ("2336", "hydraulic, pneumatic diagram",
     "A schematic for any system not covered by PEFS/UEFS (e.g., P&IDs) e.g. hydraulic pneumatic cooling,  hydraulic controls."),
    ("8373", "ice analysis study",
     "A study providing an analysis of ice data."),
    ("8374", "ice environment reference document study",
     "A study providing a description of the ice environment."),
    ("8422", "ice survey",
     "A report describing how, when and where ice data has been collected."),
    ("0514", "in place analysis",
     "A report documenting  assumptions and method determining computer structural analysis for topsides modules including piperack, flare tower, bridge for in-place loading condition."),
    ("3705", "incident report",
     "A report issued to achieve timely notification report of any accident incident occurring during the projects, including on-site, in contractors offices, etc. Severity requirements to be specified by 'owner/operator'."),
    ("0706", "independent assessment",
     "An assessment which is generated by 3rd party technical or execution expert on work done in their relevant field to assess correctness of approach/deliverable."),
    ("4372", "index of documents",
     "Books, as defined in the CFIHOS require this Index to be created. Since the purpose of the 'index' is management of a group of documents, this can only be associated with JA 'information management'. Examples: 'health', 'safety', 'environment', 'quality communication dossier basic design', 'engineering package authority approval package'."),
    ("7712", "information requirements specification",
     "Specification of the Information types required by the owner for delivery and handover."),
    ("4327", "input, output list",
     "An authoritative collection of values with a relationship to a specific equipment.  List to show input and output of an equipment (e.g. instrument, telecom equipment) connected to other equipment (e.g. distributed control system, programmable logic controller).The columns of this collection is specified and controlled."),
    ("5733", "inspection and test plan",
     "A document capturing what particular activities and requirements will be executed and delivered relating to inspection and testing for construction & vendor work."),
    ("9016", "inspection release notes",
     "A document confirming completion or waiver of final equipment inspection by the purchaser or purchaser representative."),
    ("3880", "inspection report",
     "A report documenting status and observations relating to an asset/object. Can include paint, insulation, noise, thickness measurement, destructive weld testing, NDE, preservation, cathodic protection tests, etc. Excludes pressure tests."),
    ("7178", "installation analysis",
     "A report documenting assumptions and method determining acceptable loading conditions prior to operation, including but not limited to load out, transport, and installation for handling and assembly. Intended to support handling/installation guidance to project team(s)."),
    ("2322", "installation diagram",
     "Installation refers to the mounting, setting, erection, etc. of equipment and accessories. These diagrams are for transient activity during installation (eg. sequence of activity) and not finished work."),
    ("3328", "installation manual",
     "A document that describes methods of installing a piece of equipment.  Installation refers to the mounting, setting, erection, etc."),
    ("4315", "instrument list",
     "An authoritative collection of values with a relationship to instrumentation.  The columns of this collection is specified and controlled."),
    ("0900", "insulation diagram",
     "A diagram detailing insulation, including anchoring and expansion joints, etc.  Includes refractory."),
    ("9017", "interface agreement",
     "A document describing details of an interface between contract scopes including responsibilities, execution, deliverables, and actions."),
    ("2341", "interface diagram",
     "A diagrams documenting Interfaces and demarcation of responsibilities between different organizations (e.g. battery limits, terminations)."),
    ("5800", "interface plan",
     "A document capturing what particular activities and requirements will be executed and delivered to manage interface between internal and external parties (esp. between contract scopes)."),
    ("6069", "interface procedure",
     "A procedures around Interface management activities between internal and external parties."),
    ("6627", "interface register",
     "A register documenting agreements and responsibilities between internal and external parties (esp. between contract scopes)."),
    ("6628", "interlock register",
     "A list of interlocks that automatically bring process to a safe state in response to specific initiating events."),
    ("3330", "invitation to tender",
     "A standardised document by which the Company invites Tenderers to submit a tender for a Contract. It encloses the conditions for the submission of a tender and gives the terms of reference or the technical qualifications required."),
    ("5517", "isolation philosophy",
     "A document outlining the premise and intent for isolation philosophy for safe plant operation and maintenance."),
    ("2343", "isometric diagram",
     "Construction detail diagram for 'piping and ducting', providing an accurate 'bill of materials' (BOM) / 'material take off' (MTO) and represented in a 3 dimensional isometric view."),
    ("4024", "key plan",
     "A plan view diagram of a plant/group of plants showing the interfaces of layout diagrams of components.  Typically only shows major equipment and infrastructure to provide context and orientation."),
    ("4033", "layout diagram",
     "A diagram showing the precise location of assets/objects at a plant, process unit, or area basis relative to surrounding structures and equipment."),
    ("7417", "lessons learned report",
     "A report which documents lessons gained from the execution of the project."),
    ("9009", "life-cycle assessment",
     "Methodology for assessing environmental impacts associated with all the stages of the life cycle of a commercial product, process, or service."),
    ("9006", "lifting certificate",
     "A document certifying compliance with an applicable standard and can be safely used for lifting and handling for the applicable load stated."),
    ("8236", "lifting study",
     "A study determine needs for cranes and handling equipment access for project phase also access and cost related considerations to be made.  Including project related materials handling and bulk handling."),
    ("5736", "lifting, hoisting, and rigging plan",
     "A document capturing what particular activities and requirements will be executed and delivered for lifting, hoisting, and rigging.  Should cover scope regardless of timing in asset lifecycle.  Specific risks relating to simultaneous operations should be addressed."),
    ("4329", "load list",
     "An authoritative collection of electrical loads which the electrical system must accommodate listed against each piece of equipment.  The columns of this collection are specified and controlled."),
    ("0520", "loadout and loadin analysis",
     "A report documenting  assumptions and method determining computer analysis to verify the module design for loadout/in condition."),
    ("4780", "logic diagram",
     "A graphical representation of a system using formal logic. It displays the existence of functional elements and the paths by which they interact with each other. Includes SAMA drawings."),
    ("2347", "loop diagram",
     "A diagram showing details all elements of a control loop, from sensing element through to controlling element, and cabling and wiring details for the associated instruments. Includes junction box, marshalling cabinet and control panel terminations and power supply details."),
    ("9018", "lubrication list",
     "A list of lubricants and other consumables required for equipment supplied."),
    ("4810", "maintenance manual",
     "A document that describes methods of maintaining a specific piece of equipment.  Typically originates from the equipment or package supplier."),
    ("5796", "maintenance strategy",
     "A document outlining purpose and approach for maintenance in case of preventive, breakdown or shutdown maintenance."),
    ("4328", "major equipment list",
     "An authoritative collection of equipment for a specific discipline.  The columns of this collection are specified and controlled. This classification covers registers for electrical, mechanical, and telecommunications equipment."),
    ("3341", "manpower histogram",
     "A diagram detailing current and predicted manpower through project broken down by trade/profession."),
    ("4368", "manual valve list",
     "A list describing manually operated valves.  Not check valves, not motor operated valves, not control valves, not PSVs, as these are all captured elsewhere (see instrument index for relief devices and actuated valves)."),
    ("2111", "manufacturer datasheet",
     "A datasheet which provides precise information about a equipment/model or package which shows how it meets the 'equipment specification' and the 'design datasheet requirements'; includes noise and other test results prepared by manufacturer/supplier."),
    ("6611", "master document register",
     "A register (at 'document', not 'document type' level) of the information delivered on the project, including all deliverables which receive a document number including but not limited to drawings, lists, applications, databases, and models provided by 'contractor' or 'vendor' to satisfy 'company' requirements."),
    ("6612", "master tag-equipment register",
     "An authoritative collection of values with a relationship to a specific equipment or tag.  The columns of this collection is specified and controlled."),
    ("1455", "material certificate",
     "A document certifying a material's chemical and physical properties and states a product made of metal's compliance with an international standards organization (ANSI, ASME, etc.)."),
    ("2349", "material selection diagram",
     "A schematic diagram (ie. typically a layer on a PFS/PFD or PEFS/P&ID) showing materials selected for each component of the design. May include piping class breaks (eg. CS/SS316) and vessel internals (e.g. CS epoxy lined). Includes corrosion loop diagrams that show boundary definitions."),
    ("8241", "material selection study",
     "A study describes materials and reasons for selecting those materials (e.g. environmental conditions). Considered a precursor to the 'MS report' and 'MS diagram', where used."),
    ("5011", "material traceability report",
     "Location plans/records with an identification system cross referring to the individual material certificates."),
    ("8370", "mechanical handling equipment study",
     "A study identify the most appropriate mechanical handling equipment (cranes, hoists, forklift trucks, etc.) for operations and maintenance phase for the facilities."),
    ("5520", "metering philosophy",
     "A document outlining the premise and intent for the metering and allocation philosophy for fiscal measurement for the purpose of sales or purchase relating to utilities and/or products/feedstocks."),
    ("8375", "metocean analysis study",
     "A study providing an analysis of metocean data."),
    ("8379", "metocean reference document study",
     "A study providing the metocean design and operating conditions for the proposed offshore facilities. This document should give a complete overview of all existing metocean data (wind, waves, currents, water level and weather data) and mention all existing metocean study reports."),
    ("8421", "metocean survey",
     "A report describing how, when and where metocean data has been collected.  Includes bathymetric data."),
    ("3347", "minutes of meeting",
     "A summary of a meeting highlighting attendees, status, committed action items and issues. Minutes of meetings between client and contractor as requested in contract procedures."),
    ("5280", "multimedia",
     "Multimedia being 'picture', 'sound' or 'video'.  Includes laser scans, x-rays, sonograms, installation videos, photogrammetry, illustrations, 'fly-throughs', etc."),
    ("9019", "name plate diagram",
     "A diagram showing the layout of information on name plates that are installed on the individual equipment. May also include the nameplate material and fastening method."),
    ("2110", "noise datasheet",
     "A datasheet which provides information about the noise limits for the equipment to be supplied."),
    ("6918", "non conformance report",
     "A report documenting the condition of any product or component in which one or more characteristics do not conform to requirements. Includes failures, deficiencies, defects and malfunctions. Is often identified during an audit."),
    ("6038", "non destructive test procedure",
     "A procedure detailing all non-destructive tests/examinations. Excludes pressure tests."),
    ("9020", "non destructive test report",
     "A report documenting records of non destructive testing in compliance with specified procedure."),
    ("9021", "obsolescence management plan",
     "A document capturing the expected life cycle of equipment and a plan to minimize obsolescence during design including risk assessment, monitoring, measurement and improvement."),
    ("4811", "operating manual",
     "A document that describes methods of operating a piece of equipment or process unit, including but not limited to Instructions, procedures, drawings, tables, etc. for the operation -stop, start, and emergency shutdown. Including operational limits, function testing, possible interruptions, corrective actions, hazards and corrective measures to be taken."),
    ("6039", "operating procedure",
     "A procedure to start, operate and shut-down a facility under normal and abnormal circumstances."),
    ("6926", "opportunity framing report",
     "Workshop, MOM, whitepapers, studies, brainstorm session etc."),
    ("3352", "organizational chart",
     "A diagram represents an organisation of people, indicating roles and reporting lines in a tree-like structure. May include the names of individuals."),
    ("4336", "packing list",
     "A list describing the contents of a shipment received."),
    ("2356", "passive fire protection diagram",
     "A diagram of structural and module layout drawings detailing the passive fire protection i.e. firewall/boundary fire protection ratings."),
    ("9023", "performance report",
     "A report expressed in qualitative or quantitative terms, of the tested performance of a system or item of equipment."),
    ("7876", "performance standard for safety critical element",
     "A statement, expressed in qualitative or quantitative terms, of the performance required of a system or item of equipment, which is used as the basis for managing risk."),
    ("9022", "performance test procedure",
     "A procedure identifying the test environment, tools and criteria for performance testing of a system or item of equipment."),
    ("9024", "permit",
     "A document providing authorization to perform activities."),
    ("5753", "permit plan",
     "A document capturing what particular activities and requirements will be executed and delivered to secure the appropriate regulatory permits and licenses required to allow project work, construction and eventual operations to take place."),
    ("9011", "personnel qualification certificate",
     "A document certifying the qualification of personnel in accordance with a recognised certification program."),
    ("8247", "pigging requirements study",
     "A study describing required maintenance and integrity program elements for a pipeline, e.g., cleaning and intelligent (integrity test) pigging."),
    ("2401", "pile details",
     "A diagram showing all dimensions, length width or diameter depending on square vs round.  Shows welding detail if splices for steel piles.  Show where all reinforcing steel (rebar) or pretensioned cable configuration and tension for concrete."),
    ("8371", "pile driveability study",
     "A study describing the assumptions and process of selection of suitable piling hammers for pile installation."),
    ("2365", "piping and instrumentation diagram",
     "A diagram detailing equipment, piping, and instrumentation representing topology and process flow. Includes Utility Engineering Flow Schemes (UEFS) and Fire Fighting Flow Schemes."),
    ("4338", "piping line list",
     "An authoritative collection of values with a relationship to piping. The columns of this collection are specified and controlled."),
    ("7737", "piping specification",
     "A specialized functional design specification for piping."),
    ("9025", "pre start-up safety review",
     "A report verifying that process safety hazards have been addressed prior to start-up."),
    ("7003", "pre-qualification evaluation",
     "A report summarizing technical or commercial evaluation of a pre-qualification to tender."),
    ("3356", "pre-qualification questionnaire",
     "A request for information from a third party who may provide services or supply materials in order to identify if they meet required criteria."),
    ("6046", "pressure test procedure",
     "A procedure documenting specific steps to conduct inspection of an asset/object.  Typically details boundaries of the test, isolations, method of pressurization, required hold intervals etc.  Includes hydrostatic, pneumatic, vacuum and leak test/examinations."),
    ("8611", "pressure test report",
     "A report recording duration and results of hydro static, pneumatic, and leak test examinations.  Typically includes a pressure chart to demonstrate satisfactory results."),
    ("2408", "primary steel diagram",
     "A diagram depicting primary steel(e.g., bracing, beams)."),
    ("5306", "process control narrative",
     "A document describing the process control functionality (e.g. level control)."),
    ("8248", "process control, optimisation study",
     "A document detailing evaluation of operating scenarios and control schemas in order to optimize the facility design and control."),
    ("2366", "process flow diagram",
     "A diagram detailing major items of equipment, primary lines and valves, operating temperatures, pressures and mass flows. Diagrams shall be provided for all hydrocarbon and utilities systems. Includes 'utility flow schemes/diagrams' [UFS/UFD]."),
    ("2368", "process safeguarding flow diagram",
     "A diagram detailing safeguarding elements for process and utility protection against uncontrolled loss of containment."),
    ("5805", "procurement schedule",
     "A time-based document outlining sequence and duration of activities related to procurement activities (RFQs, purchase orders, required on site milestones, etc.)."),
    ("5756", "procurement, contracting strategy",
     "A document outlining purpose and approach for developing contracting and procurement strategies is to identify the in-house scope and the contract packages that will eventually be placed in the market.  The development of contracting & procurement strategies is the first step towards aligning the project demands of external parties (in terms of the required goods and services), with the market supply, in terms of capable and experienced contractors and suppliers."),
    ("6944", "progress report",
     "A report documenting progress made against a previously communicated plan or schedule. 'progress reports' can address time, scope, money, etc."),
    ("5759", "project control plan",
     "A document capturing key project control execution plans applicable across the project scope."),
    ("7739", "project functional specification",
     "A specification describing scope and objectives of the project and its execution; details to be provided by 'owner operator'."),
    ("5762", "project lifecycle information register",
     "A list of content types to be delivered by the project."),
    ("5798", "project plan",
     "A document capturing key discipline execution plans applicable across the project scope (e.g., IM Plan, Execution Plan)."),
    ("5765", "project schedule",
     "A time-based document summarizing all discipline related activities outlining sequence and duration."),
    ("3359", "purchase order",
     "An order that describes the scope, price and delivery conditions of an item that is bought."),
    ("9026", "quality plan",
     "A document describing procedures to ensure quality delivery of services or procured item(s) in conformance with the agreed requirements."),
    ("5795", "recruitment plan",
     "A document capturing what particular activities and requirements will be executed and delivered to support recruitment.  Typically the plan is built upon a strategy."),
    ("1453", "regulatory compliance certificate",
     "A document certifying conformity to local regulations which accompanies shipment of equipment and/or goods. e.g., official certificate issued by OEM/supplier or approved licensed agent of OEM/supplier."),
    ("2701", "regulatory compliance report",
     "Report demonstrating compliance with local regulations and law."),
    ("2397", "reinforcement diagram",
     "Includes steel reinforcement in concrete structures (e.g., rebar)."),
    ("1222", "reliability, availability, safety integrity level calculation",
     "Demonstrates starting and operating reliability / availability of purchased equipment  (e.g. mean time between failure data) & 'safety integrity level' (SIL) calculations."),
    ("2908", "relief valve calculation",
     "Process relief valve calculation. the output is documented in the process safeguarding memorandum."),
    ("8249", "relief, flare and vent study",
     "A study related to the impact on personnel or equipment of lit or unlit relief, flaring and venting events."),
    ("7303", "requisition",
     "A request with a brief description of the parts to be ordered, with a statement of the pertinent drawings, specifications, etc., as well as a list of drawings and documents to be provided by the manufacturer/supplier."),
    ("7177", "righting arm curve analysis",
     "A report documenting  assumptions and method determining that a vessel meets stability requirements during construction, tow, installation and operation phase for both intact and damage conditions as they apply based on latest deadweight weight estimate.  For FPSO will cover several loading conditions."),
    ("5768", "risk and opportunity management plan",
     "A document capturing how risks and opportunities will be documented, communicated, managed, and closed.  Typically the plan is built upon a strategy."),
    ("0709", "risk assessment",
     "An assessment which details the quantitative or qualitative risk related to a specific scenario presented to 'company'."),
    ("6619", "risk, opportunity register",
     "An authoritative collection of items with a relationship to risks and/or opportunities which have a potential to impact overall project performance.  The columns of this collection are specified and controlled."),
    ("6958", "route selection study",
     "A study describing priorities and criteria, practical restrictions, and options considered for route selection.  Includes route layout drawing and/or platform approach where applicable."),
    ("2373", "routing diagram",
     "A diagram showing alignment of cables and pipelines between plants. Includes alignment sheet for pipelines."),
    ("8251", "safe operation study",
     "A study validating electrical systems design will allow for safe operation."),
    ("3363", "safeguarding memorandum",
     "A document outlining the premise and intent for decisions that are to be followed regarding process relief cases, the ultimate safeguards (relief devices) and penultimate safeguards (safeguards by instrumentation) for process integrity of a particular process unit. It complements the 'process safeguarding flow diagram'."),
    ("5531", "safeguarding philosophy",
     "A document outlining the premise and intent for decisions that are to be followed regarding safety instrumented systems (SIS) and flare and relief systems for process integrity of a facility.  Protecting against temperature and pressure extremes, hydrates, fire, explosion, etc."),
    ("6881", "safety critical elements register",
     "An authoritative collection of all safety critical elements (SCE), as defined by company.  The columns of this collection are specified and controlled."),
    ("2107", "safety datasheet",
     "A datasheet which summarizes of physical and chemical properties of the substance - description of its harmful nature including potential impact on the health and safety of personnel and of the environment - precautions necessary to ensure its safe use and eventual disposal."),
    ("1439", "safety declaration",
     "A certificate issued by asset owner to 'regulatory authority' demonstrating compliance with 'regulatory authority' safety  requirements. A 'safety declaration' is a document that describes the nature and scale of hazards of an industrial facility, lays out measures developed to ensure its industrial safety and readiness for emergency response in  man-induced emergency situations."),
    ("9007", "safety integrity level (SIL) certificate",
     "This document shall verify the level of the safety integrity level (SIL) and shall include necessary performance data according to authority regulations."),
    ("9027", "safety requirements specification",
     "A specification containing the functional requirements for the safety instrumented functions identified during the hazard and risk assessment, including their associated safety integrity levels."),
    ("2374", "safety zone diagram",
     "A diagram showing the main safety features of the facility. Typically related to toxic zones. e.g. 'H2S zone' diagram."),
    ("2580", "schematic diagram",
     "A pictorial representation of the main elements and functions of a control circuit for electrical equipment with input/output sources (switches, relays etc.) and their relationships. Details logic functions of the circuit."),
    ("5793", "scope of work",
     "A document defining of work to be performed as part of a contract."),
    ("2386", "secondary steel diagram",
     "A diagram depicting secondary and higher order steel elements in the structure (including but not limited to cladding, roofs, grating)."),
    ("0522", "setdown analysis",
     "A report documenting  assumptions and method determining computer analysis to verify the module design for setdown condition."),
    ("4606", "short circuit calculation",
     "Calculations necessary to determine the capacity of electrical equipment under fault conditions."),
    ("5773", "simultaneous operations plan",
     "A document capturing what particular activities and requirements will be executed and delivered to manage simultaneous operations with a brownfield operating asset."),
    ("2384", "single line diagram",
     "A diagram depicting the main equipment items (switchboards, transformers etc.) and their relationships within the facility electrical distribution system including details of fault levels and current and voltage ratings."),
    ("9002", "site acceptance test procedure",
     "A document defining manufacturers recommended site tests for the equipment."),
    ("9004", "site acceptance test records",
     "Records demonstrating that the equipment has been tested according to the site acceptance test procedure."),
    ("9028", "site study",
     "A study providing details of site data or information where work is proposed."),
    ("0713", "social impact assessment",
     "An assessment which details the impact of facility on the surrounding community and infrastructure."),
    ("6968", "soil investigation and survey",
     "Onshore and/or offshore investigation and survey reports and topographic data. Includes soil, rock, minerals and organic matter from soil investigations and surveys."),
    ("4354", "spare part list",
     "A list of recommended listing of spares received from vendor/manufacturer to support installation, commissioning, operation or maintenance."),
    ("9029", "special tools list",
     "A list of all special tools necessary for handling, dismantling, maintenance of equipment."),
    ("0510", "stability analysis",
     "A report to ensure pipeline stability under extreme environmental loading."),
    ("7758", "staffing plan",
     "A document describing required skill, knowledge, experience for a range of positions to execute the project. May address dates of requirement, quantities, etc. Includes job descriptions."),
    ("5775", "stakeholder engagement plan",
     "A document capturing what particular activities and requirements will be executed and delivered to support effective communication with partners and external stakeholders."),
    ("8005", "stress calculation",
     "A calculation to determine how a pipe or piping system behaves based on its material, pressure, temperature, fluid and support."),
    ("9030", "sub-supplier list",
     "A list of sub-suppliers or sub-contractors providing processes, products or services to the supplier or contractor in conformance with owner requirements"),
    ("5879", "subcontract management plan",
     "A document capturing what particular activities and requirements will be executed and delivered to manage subcontracts.  Also used to track status of all the essential activities to be performed. It categorises the actions to be taken (e.g. team roles and responsibilities) and also the status of them (e.g. 'open', 'action party', 'due date')."),
    ("2358", "support diagram",
     "A detail diagram depicting the support of pipe, cable, instrument and other supports (e.g., pipe shoes, sleeper, hangers)."),
    ("6068", "surface protection procedure",
     "A procedure detailing painting, coating and cathodic protection."),
    ("5778", "sustainable development plan",
     "A document capturing what particular activities and requirements will be executed and delivered to support a comprehensive development of the asset.  This includes but is not limited to community affairs, local content issues, societal effects of project, local business development, etc."),
    ("9031", "system architecture diagram",
     "A diagram illustrating software system components and how they interact with each other."),
    ("8260", "system study",
     "Includes load flows, transient and dynamic stability, short circuit, protection study, co-ordination and setting."),
    ("7205", "technical deviation request",
     "A request, approval or rejection of changes to a technical specification. Would typically include justification and reasons for the request, and acceptance or rejection from a purely technical perspective."),
    ("3323", "technical note",
     "A communication documenting how an engineering or maintenance issue will be resolved and what the implication of the solution is."),
    ("6999", "tender evaluation",
     "A document capturing the results of a technical and/or commercial evaluation of tender based on pre-defined criteria and/or conditioning for purposes of selection and award."),
    ("2389", "termination diagram",
     "A diagram for equipment, panels, junction boxes, etc. identifies all connections and cable terminations at input/output rails. Required for removal/hook up purposes and modifications. To include vendor interfaces."),
    ("7753", "terms of reference",
     "A document capturing scope and details of the activity to which it refers and any conditions relating to the appointment of a person(s) to undertake the activity. Includes the distribution of work, schedule and the responsibilities among the people participating in an evaluation process."),
    ("6061", "test procedure",
     "A procedure to perform a test that equipment or systems are functioning and performing according to the specifications, function descriptions and operating instructions."),
    ("5780", "testing, inspection schedule",
     "A time-based document outlining order in which tasks are to be carried out and the amounts of time allocated to them to achieve inspection and testing scope."),
    ("8263", "thermal expansion study",
     "A document detailing the result from thermal expansion and informing design regarding the need for loops and expansion joints."),
    ("1208", "thermal rating calculation",
     "Calculations to demonstrate thermal ratings of heat exchangers."),
    ("7402", "three dimensional model review report",
     "A report documenting the review results from 3D review addressing steelwork structure, equipment envelopes, escape routes, building envelopes, envelopes for main piping, HVAC and cable rack runs, preliminary road layouts, etc."),
    ("0903", "three line diagram",
     "A diagram depicting each line (e.g., positive, negative, and ground on a DC System)  describing an electrical system.  Example: the connection of a pump its control station and the MCC."),
    ("4363", "tie-in list",
     "Tie-in list identifies areas of a brownfield facility where connections will be made. May include interfaces between project stages, contractors and systems (e.g. new to existing plant connections)."),
    ("4904", "topographic map",
     "A diagram describing grade and elevation of a given area.  Also for seafloor at offshore site and access route."),
    ("1927", "training manual",
     "A collection of training materials.  May include 'operational & maintenance training plan' providing durations and locations of sessions."),
    ("0521", "transportation analysis",
     "A report documenting  assumptions and method determining computer analysis to verify the module design for transportation condition."),
    ("4006", "trench diagram",
     "A diagram depicting civil earthworks for utility services (e.g., piping, cables) for construction activity management.  Typically depicts slope, etc."),
    ("5807", "turnover plan",
     "A listing of data and documents to be handed over by the EPC to the owner/operator. Includes timing and formats."),
    ("4038", "underground service layout diagram",
     "A diagram showing the precise location of assets/objects at a plant, process unit, or area basis, describing elevation and relative to surrounding structures and equipment."),
    ("0519", "vibration analysis",
     "A report documenting  assumptions and method determining computer analysis of cyclic loads due to vibratory equipment. (e.g. module and foundations for rotating equipment)."),
    ("6988", "vibration report",
     "A report documenting vibration and displacement measurements of piping and equipment."),
    ("7202", "waiver request",
     "Request, approval or rejection for the relaxation of an element of the particular regulatory 'code', 'standard', 'rule' or 'regulation' where such element conflicts with the 'international code' or 'standard' proposed for the facilities."),
    ("5788", "waste management plan",
     "A document capturing what particular activities and requirements will be executed and delivered to support management and safe disposal of all waste."),
    ("6063", "weighing procedure",
     "A procedure to record weight during design and manufacture prior to shipment."),
    ("1231", "weight calculation",
     "Includes mass, buoyancy, and calculations used in the design of weight coating (eg. on submerged pipelines)."),
    ("1447", "weight certificate",
     "A document certifying the correct gross weight for a piece of equipment including packing materials.  This typically should also document the center of gravity."),
    ("1448", "weight report",
     "A report shows weight and center of gravity of equipment. If large items are to be handled for equipment installation or maintenance, then the weight and center of gravity of these individual parts should be shown."),
    ("5789", "weld map",
     "A drawing that usually identifies all welds and relates them to the relevant welding procedure number and non destructive testing requirements."),
    ("1456", "welder qualification certificate",
     "A document certifying a welder is qualified to perform work according to certain weld procedure."),
    ("6066", "welding procedure qualification",
     "A record documenting the execution and satisfactory testing of a weld procedure specification, typically includes all testing procedure references and both destructive and non-destructive testing results."),
    ("6065", "welding procedure specification",
     "A specification that describes the welding procedure and process of a specific weld."),
    ("6064", "welding repair procedure",
     "A document which describes a set of logically sequenced instructions to execute a weld repair."),
    ("8880", "wiring diagram",
     "A diagram which depicts an electrical circuit.  It shows the components of the circuit as simplified shapes, and the power and signal connections between devices."),
    ("5792", "work breakdown structure specification",
     "A document formally establishing scope of work into smaller manageable blocks to manage cost and schedule control."),
    ("3375", "work instruction",
     "Step by step instruction for the accomplishment of a task. more detailed than a procedure."),
)

# (node_code, preferred_label). No CFIHOS code exists for these values, so the
# codes are derived from the labels. Order is alphabetical.
_REPRESENTATION_TYPES: tuple[tuple[str, str], ...] = (
    ("INTELLIGENT_VECTOR_DRAWING_CAD", "Intelligent vector drawing (CAD)"),
    ("MULTI_MEDIA", "Multi media"),
    ("RASTER_IMAGE", "Raster Image"),
    ("STRUCTURED_DATA", "Structured Data"),
    ("TEXT", "Text"),
)


def _seed_scheme(connection, scheme, nodes, *, with_description: bool) -> None:
    scheme_code, name, description = scheme
    scheme_id = uuid.uuid5(uuid.NAMESPACE_URL, f"urn:symgov:classification-scheme:{scheme_code}")
    connection.execute(
        sa.text(
            "INSERT INTO classification_schemes "
            "(id, scheme_code, name, scope, version_label, status, description, "
            "created_at, updated_at) "
            "VALUES (:id, :scheme_code, :name, 'platform', :version_label, 'active', "
            ":description, now(), now()) "
            "ON CONFLICT DO NOTHING"
        ),
        {
            "id": scheme_id,
            "scheme_code": scheme_code,
            "name": name,
            "version_label": _SEED_VERSION_LABEL,
            "description": description,
        },
    )
    for index, row in enumerate(nodes):
        node_code, preferred_label = row[0], row[1]
        connection.execute(
            sa.text(
                "INSERT INTO classification_nodes "
                "(id, scheme_id, node_code, parent_node_id, preferred_label, description, "
                "sort_order, status, created_at, updated_at) "
                "VALUES (:id, :scheme_id, :node_code, NULL, :preferred_label, :description, "
                ":sort_order, 'active', now(), now()) "
                "ON CONFLICT DO NOTHING"
            ),
            {
                "id": uuid.uuid5(
                    uuid.NAMESPACE_URL,
                    f"urn:symgov:classification-node:{scheme_code}:{node_code}",
                ),
                "scheme_id": scheme_id,
                "node_code": node_code,
                "preferred_label": preferred_label,
                "description": row[2] if with_description else None,
                "sort_order": (index + 1) * _SORT_ORDER_STEP,
            },
        )


def upgrade() -> None:
    connection = op.get_bind()
    _seed_scheme(connection, _DOCUMENT_TYPE_SCHEME, _DOCUMENT_TYPES, with_description=True)
    _seed_scheme(
        connection, _REPRESENTATION_TYPE_SCHEME, _REPRESENTATION_TYPES, with_description=False
    )


def downgrade() -> None:
    """Remove the two seeded schemes and their nodes.

    The RESTRICT foreign key on classification_nodes means this fails rather
    than cascading if an assignment has since been made against one of these
    nodes -- which is the correct outcome: a downgrade must not silently
    discard governed classification decisions.
    """
    connection = op.get_bind()
    for scheme_code, _name, _description in (_DOCUMENT_TYPE_SCHEME, _REPRESENTATION_TYPE_SCHEME):
        scheme_id = uuid.uuid5(
            uuid.NAMESPACE_URL, f"urn:symgov:classification-scheme:{scheme_code}"
        )
        connection.execute(
            sa.text("DELETE FROM classification_nodes WHERE scheme_id = :id"), {"id": scheme_id}
        )
        connection.execute(
            sa.text("DELETE FROM classification_schemes WHERE id = :id"), {"id": scheme_id}
        )

